### ISSUE TITLE
Can we use this to send custom APDU command?

### ISSUE THREAD

**Issue by harishsg993010** [leommxj/nfc_relay#1]
Can we use this to send custom APDU command using this app

**Comment by leommxj** [comment]
> Can we use this to send custom APDU command using this app

This app is relay APDU between two flipper and reader&tag. 
To send custom APDU maybe just use command like `nfc apdu 00a404000e325041592e5359532e444446303100 00a4040008a000000301010` in the flipper cli? code are in `https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/main/nfc/nfc_cli.c`
